### PR TITLE
Importing initial CI scripts and config

### PR DESCRIPTION
**Pull request by G-Ragghianti**
Implementation of a basic CI workflow via github actions.

### CODE REVIEW

**Comment by stomov** [comment]
Every routine in magma has a tester and "make test" will generate all of them. The framework to run them is run_tests.py but this includes exhaustive runs that take hours. There are provisions only certain things to be tested, e.g.,
./run_tests.py -s testing_sgemm > sgemm.log
testing_sgemm -l -NN -c                           ok
testing_sgemm -l -NC -c                           ok
testing_sgemm -l -CN -c                           ok
testing_sgemm -l -CC -c                           ok
testing_sgemm -l -NT -c                           ok
testing_sgemm -l -TN -c                           ok
testing_sgemm -l -TT -c                           ok

****************************************************************************************************
summary
****************************************************************************************************
all 609 tests in 7 commands passed!

Typically, if we want to just test an installation I would test sgemm, e.g.,
make testing_sgemm
./testing/testing_sgemm -n 300
% MAGMA 2.6.1 svn 32-bit magma_int_t, 64-bit pointer.
% Compiled with CUDA support for 3.0
% CUDA runtime 7000, driver 7050. MAGMA not compiled with OpenMP. 
% device 0: GeForce GT 750M, 925.5 MHz clock, 2047.6 MiB memory, capability 3.0
% Fri Apr  7 14:30:01 2023
% Usage: ./testing/testing_sgemm [options] [-h|--help]

% If running lapack (option --lapack), MAGMA and cuBLAS error are both computed
% relative to CPU BLAS result. Else, MAGMA error is computed relative to cuBLAS result.

% transA = No transpose, transB = No transpose
%   M     N     K   MAGMA Gflop/s (ms)  cuBLAS Gflop/s (ms)   CPU Gflop/s (ms)  MAGMA error  cuBLAS error
%========================================================================================================
  300   300   300     35.76 (   1.51)      78.83 (   0.68)     ---   (  ---  )    0.00e+00        ---    ok

where the ok at the end indicates test is successful. If it fails we print "failed".

**Comment by G-Ragghianti** [comment]
I think the issue I"m facing is that when using cmake with out-of-source build, the run_tests.py is not put into place, and the "make test" or "make check" is not defined.

**Review by mgates3 — APPROVED** [review]
Looks good as starting point.

**Comment by G-Ragghianti** [comment]
OK, I have also implemented Stan's suggested minimal tests (sgemm), and the CI scripts look good to merge.  If there aren't any objections, I will merge this.

**Pull request merged**
